---
  name: "Jenkins 2.0 Beta"
  description: "Jenkins 2.0 Beta"
  version: 0
  maintainer: "Travis N. Thomsen travis.n.thomsen@gmail.com"
  license: "Apache"
  projectURL: "https://github.com/tthomsen/rancher"
